#!/bin/bash

cd .scripts/docker/

red() {
    echo '\033[1;31m'$1'\033[0m'
}

WHAT=$1
case "$WHAT" in
    pull|p)
        docker compose pull
        ;;
    up|u)
        docker compose up -d
        ;;
    down|d)
        docker compose down
        ;;
    *)
        echo -e "Only the following operations are supported:\n"
        echo -e "docker-compose [$(red p)]ull"
        echo -e "docker-compose [$(red u)]p"
        echo -e "docker-compose [$(red d)]own"
        exit 1
        ;;
esac