#!/bin/bash

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"

export BOOTSTRAP_SERVERS="localhost:9093"
export SCHEMA_REGISTRY_URL="http://localhost:8081"

export TOPIC="python_producer_example"
export KEY_SCHEMA="$SCRIPT_PATH/schema/key.json"
export VALUE_SCHEMA="$SCRIPT_PATH/schema/value.json"

python "$SCRIPT_PATH/produce_basic.py"
